name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  SEPOLIA_PROVIDER_URL: ${{ secrets.SEPOLIA_PROVIDER_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: balanceOf
        with:
          providerUrl: ${{ env.SEPOLIA_PROVIDER_URL }}
          to: '0xab879B28006F5095ab346Eb525daFeA2cf18Bc3f'
          data: '0x70a0823100000000000000000000000027711f9c07230632f2ee1a21a967a9ac4729e520'
      - if: ${{ steps.balanceOf.outputs.result != '0x0000000000000000000000000000000000000000000000000000000000000002' }}
        run: |
          echo "No address found in user config."
          exit 1